local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
# Lower if you receive warning on 'Transform Timeout' and 'Map Update Loop'
   update_frequency: 2.0 #5.0
   publish_frequency: 2.0 #5.0
   width: 1.0 #10.0
   height: 1.0 #10.0
   resolution: 0.05
   static_map: false
   rolling_window: true
